### ISSUE TITLE
Metrilyx does not show any data

### ISSUE THREAD

**Issue by usman1522** [Ticketmaster/metrilyx-2.0#64]
Hi, 

I just setup Metrilyx on and pointed it to my TSDB host (updating the address in metrilyx.conf). But I am not able to see/search any metrics in the Metrilyx UI. All three services seem to be started fine: 
metrilyx-cacher
metrilyx-modelmanager
metrilyx-dataserver

The logs also seem to be fine. (pasted below). 

Is there any extra step I need to do before Metrilyx starts showing the existing data in my TSDB? 

[LOGS: metrilyx-modelmanager]
--------------------------------------------
uWSGI] getting INI configuration from /opt/metrilyx/etc/metrilyx/uwsgi.conf
*** Starting uWSGI 2.0.4 (64bit) on [Wed Dec 17 18:31:58 2014] ***
compiled with version: 4.4.7 on 17 December 2014 15:09:47
os: Linux-3.13.0-40-generic #69~precise1-Ubuntu SMP Fri Nov 14 10:29:31 UTC 2014
nodename: musman-wsl1
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /opt/metrilyx/run/modelmanager.sock fd 3
Python version: 2.7.3 (default, Feb 27 2014, 20:09:21)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x200b730
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1527960 bytes (1492 KB) for 20 cores
*** Operational MODE: preforking ***
ImportError: No module named metrilyx.wsgi
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7569)
spawned uWSGI worker 1 (pid: 7571, cores: 1)
spawned uWSGI worker 2 (pid: 7572, cores: 1)
spawned uWSGI worker 3 (pid: 7573, cores: 1)

[LOGS: metrilyx-dataserver]
--------------------------------------

2014-12-17 18:31:56,705 [WARNING __main__ 108] Using auto-spawn count.
2014-12-17 18:31:56,705 [WARNING __main__ 115] Performance dataprovider [loaded]
2014-12-17 18:31:56,705 [WARNING __main__ 134] Protocol: __main__.GraphProtocol
2014-12-17 18:31:56,705 [WARNING __main__ 136] Spawning 11 server/s...
2014-12-17 18:31:56,707 [WARNING __main__ 64] Started server - ws://localhost:9000
2014-12-17 18:31:56,707 [WARNING __main__ 64] Started server - ws://localhost:9001
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/metrilyx/bin/metrilyx-dataserver.py", line 52, in spawnWebsocketServer
    listenWS(factory)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 588, in listenWS
    listener = reactor.listenTCP(factory.port, factory, backlog, interface)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 979, in startListening
2014-12-17 18:31:56,708 [WARNING __main__ 64] Started server - ws://localhost:9002
    raise CannotListenError(self.interface, self.port, le)
Traceback (most recent call last):
CannotListenError: Couldn't listen on any:9000: [Errno 98] Address already in use.
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/metrilyx/bin/metrilyx-dataserver.py", line 52, in spawnWebsocketServer
    listenWS(factory)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 588, in listenWS
    listener = reactor.listenTCP(factory.port, factory, backlog, interface)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 979, in startListening
    raise CannotListenError(self.interface, self.port, le)
CannotListenError: Couldn't listen on any:9001: [Errno 98] Address already in use.
2014-12-17 18:31:56,710 [WARNING __main__ 64] Started server - ws://localhost:9004
2014-12-17 18:31:56,710 [WARNING __main__ 64] Started server - ws://localhost:9005
2014-12-17 18:31:56,711 [WARNING __main__ 64] Started server - ws://localhost:9006
2014-12-17 18:31:56,712 [WARNING __main__ 64] Started server - ws://localhost:9007
2014-12-17 18:31:56,713 [WARNING __main__ 64] Started server - ws://localhost:9008
2014-12-17 18:31:56,713 [WARNING __main__ 64] Started server - ws://localhost:9009
2014-12-17 18:31:56,714 [WARNING __main__ 64] Started server - ws://localhost:9010

**Comment by euforia** [comment]
can you test on a vagrant machine for centos 6?  or docker?  If not run some tests on my end to see what the exact issue with 12.04?  

Let's keep this open.  I'll try to through some cycles at it in the coming week.

**Comment by euforia** [comment]
Also make sure that all the packages in REQUIREMENTS.txt cleanly install.

**Comment by euforia** [comment]
Hey @usman1522 ,
I've pushed out a patch for ubuntu 12 and up'd the version.  If you re-install from the master branch (2.4.2 now) you should have a working instance.  I've successfully tested the following distros:

- CentOS based >= 6.5
- Ubuntu  12.04, 14.04

Also remember to configure the websocket section incase you don't have a resolvable FQDN.

I'm going to keep this open until I get a confirmation that you have a working instance.

Please let me know.

**Comment by usman1522** [comment]
Hi, 

Thanks for working on the fix for 12.04. 

I re-installed everything and I am still facing the same issue :(. The Metrilyx UI does not show any metrics from TSDB. I verified again, TSDB does have the data and Metrilyx is pointing to the correct port for TSDB. Everything is on my local host for now so there is no potential network setup issue either. The only change i made was to update the nginx config to host metrilyx on port 4466 instead of default 80. 

All other logs seem to be fine other than ModelManager. Which show this: 
(Please let me know if there are other logs, I can provide)

[uWSGI] getting INI configuration from /opt/metrilyx/etc/metrilyx/uwsgi.conf
*** Starting uWSGI 2.0.4 (64bit) on [Wed Jan 14 17:22:19 2015] ***
compiled with version: 4.6.3 on 14 January 2015 16:29:26
os: Linux-3.13.0-43-generic #72~precise1-Ubuntu SMP Tue Dec 9 12:14:18 UTC 2014
nodename: musman-wsl1
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 131
setuid() to 121
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /opt/metrilyx/run/modelmanager.sock fd 3
Python version: 2.7.3 (default, Dec 18 2014, 19:25:50)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a33630
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1527960 bytes (1492 KB) for 20 cores
*** Operational MODE: preforking ***
ImportError: No module named metrilyx.wsgi
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29342)
spawned uWSGI worker 1 (pid: 29344, cores: 1)
spawned uWSGI worker 2 (pid: 29345, cores: 1)
spawned uWSGI worker 3 (pid: 29346, cores: 1)
spawned uWSGI worker 4 (pid: 29347, cores: 1)
spawned uWSGI worker 5 (pid: 29348, cores: 1)
spawned uWSGI worker 6 (pid: 29349, cores: 1)
spawned uWSGI worker 7 (pid: 29350, cores: 1)
spawned uWSGI worker 8 (pid: 29351, cores: 1)
spawned uWSGI worker 9 (pid: 29352, cores: 1)
spawned uWSGI worker 10 (pid: 29353, cores: 1)
spawned uWSGI worker 11 (pid: 29354, cores: 1)
spawned uWSGI worker 12 (pid: 29355, cores: 1)
spawned uWSGI worker 13 (pid: 29356, cores: 1)
spawned uWSGI worker 14 (pid: 29357, cores: 1)
spawned uWSGI worker 15 (pid: 29358, cores: 1)
spawned uWSGI worker 16 (pid: 29359, cores: 1)
spawned uWSGI worker 17 (pid: 29360, cores: 1)
spawned uWSGI worker 18 (pid: 29361, cores: 1)
spawned uWSGI worker 19 (pid: 29362, cores: 1)
spawned uWSGI worker 20 (pid: 29363, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 29361|app: -1|req: -1/1] 127.0.0.1 () {40 vars in 669 bytes} [Wed Jan 14 17:22:26 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
[pid: 29363|app: -1|req: -1/3] 127.0.0.1 () {38 vars in 632 bytes} [Wed [pid: 29362|app: -1|req: -1/3] 127.0.0.1 () {38 vars in 642 bytes} [Wed Jan 14 17:22:26 2015] GET /api/event_types => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[pid: 29353|app: -1|req: -1/4] 127.0.0.1 () {38 vars in 646 bytes} [Wed Jan 14 17:22:26 2015] GET /api/schemas/graph => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29362|app: -1|req: -1/5] 127.0.0.1 () {38 vars in 632 bytes} [Wed Jan 14 17:22:26 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)

**Comment by euforia** [comment]
Is this still an issue?
